#+TITLE: xAPI Secure Access Policy
#+OPTIONS: toc:2
#+TOC: listings
#+TOC: tables


   In accordance with [[https://www.whitehouse.gov/sites/default/files/omb/memoranda/2015/m-15-13.pdf][OMB Memorandum M-15-13]], which mandates the exclusive use of
HTTPS with HSTS across all Federal government web services, it stands to reason
that, as a DoD initiative, [[http://www.adlnet.gov/capabilities/tla/experience-api.html][xAPI]] should hold itself, at a minimum, to this standard.

This document intends to establish a set of best practices for secure xAPI usage,
hopefully leading to a standard extending xAPI, provisionally termed xAPIsec.

* Table of Contents                                                     :TOC:
 - [[#web-standards][Web Standards]]
   - [[#https][HTTPS]]
   - [[#hsts][HSTS]]
   - [[#perfect-forward-secrecy][Perfect Forward Secrecy]]
 - [[#pki][PKI]]
 - [[#conformance-testing][Conformance Testing]]
   - [[#third-party-services][Third-Party Services]]

* Web Standards
** HTTPS

HTTP over TLS (Hypertext Transfer Protocol over Transport Layer Security) has
existed for over 15 years. The extant RFC defining HTTPS, [[http://tools.ietf.org/html/rfc2818][RFC 2818]], dates from
May 2000.

** HSTS

HSTS, or Hypertext Strict Transport Security, is a method whereby web servers
instruct clients that they are only to be accessed over HTTPS, never insecure HTTP,
within a given time frame.

** Perfect Forward Secrecy

Forward secrecy is a cryptographic method of mitigating attack surface by preventing
the reuse of keys between sessions.

* PKI
* Conformance Testing
** Third-Party Services
   [[https://www.ssllabs.com/ssltest/][Qualys SSl Labs Server Test]] is a
   recommended first-line test for compliance with best practices for
   secure HTTP transport. Any LRS or application endpoint with less than an A+
   rating is recommended to follow the suggestions provided by the Qualys scan
   to mitigate vulnerabilities until an A+ rating is achieved.
